//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DatabaseAccess;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DbSchoolManagementSystemEntities : DbContext
{
    public DbSchoolManagementSystemEntities()
        : base("name=DbSchoolManagementSystemEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<TblAnnual> TblAnnuals { get; set; }
    public virtual DbSet<TblClass> TblClasses { get; set; }
    public virtual DbSet<TblClassSubject> TblClassSubjects { get; set; }
    public virtual DbSet<TblDesignation> TblDesignations { get; set; }
    public virtual DbSet<TblEmployee> TblEmployees { get; set; }
    public virtual DbSet<TblEmployeeAttendance> TblEmployeeAttendances { get; set; }
    public virtual DbSet<TblEmployeeCertificate> TblEmployeeCertificates { get; set; }
    public virtual DbSet<TblEmployeeEducation> TblEmployeeEducations { get; set; }
    public virtual DbSet<TblEmployeeLanguage> TblEmployeeLanguages { get; set; }
    public virtual DbSet<TblEmployeeLeaving> TblEmployeeLeavings { get; set; }
    public virtual DbSet<TblEmployeeResume> TblEmployeeResumes { get; set; }
    public virtual DbSet<TblEmployeeSalary> TblEmployeeSalaries { get; set; }
    public virtual DbSet<TblEmployeeSkill> TblEmployeeSkills { get; set; }
    public virtual DbSet<TblEmployeeWorkExperience> TblEmployeeWorkExperiences { get; set; }
    public virtual DbSet<TblEvent> TblEvents { get; set; }
    public virtual DbSet<TblExam> TblExams { get; set; }
    public virtual DbSet<TblExamMark> TblExamMarks { get; set; }
    public virtual DbSet<TblExamSetting> TblExamSettings { get; set; }
    public virtual DbSet<TblExpense> TblExpenses { get; set; }
    public virtual DbSet<TblExpenseType> TblExpenseTypes { get; set; }
    public virtual DbSet<TblProgramme> TblProgrammes { get; set; }
    public virtual DbSet<TblProgrammeSession> TblProgrammeSessions { get; set; }
    public virtual DbSet<TblRoom> TblRooms { get; set; }
    public virtual DbSet<TblSection> TblSections { get; set; }
    public virtual DbSet<TblSession> TblSessions { get; set; }
    public virtual DbSet<TblSessionProgrammeSubjectSetting> TblSessionProgrammeSubjectSettings { get; set; }
    public virtual DbSet<TblStudent> TblStudents { get; set; }
    public virtual DbSet<TblStudentAttendance> TblStudentAttendances { get; set; }
    public virtual DbSet<TblStudentLeaving> TblStudentLeavings { get; set; }
    public virtual DbSet<TblStudentPromot> TblStudentPromots { get; set; }
    public virtual DbSet<TblSubject> TblSubjects { get; set; }
    public virtual DbSet<TblSubmissionFee> TblSubmissionFees { get; set; }
    public virtual DbSet<TblTime> TblTimes { get; set; }
    public virtual DbSet<TblUser> TblUsers { get; set; }
    public virtual DbSet<TblUserType> TblUserTypes { get; set; }
}
