//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClassSubject
    {
        public int ClassSubjectId { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public string ClassSubjectTitle { get; set; }
        public Nullable<bool> ClassSubjectStatus { get; set; }
    
        public virtual TblClass TblClass { get; set; }
        public virtual TblSubject TblSubject { get; set; }
    }
}
