//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEmployeeCertificate
    {
        public int EmployeeCertificateId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> EmployeeResumeId { get; set; }
        public string EmployeeCertificateName { get; set; }
        public string EmployeeCertificateAuthority { get; set; }
        public string EmployeeCertificateLevel { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EmployeeCertificateFromYear { get; set; }
    
        public virtual TblEmployeeResume TblEmployeeResume { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
