//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEmployeeAttendance
    {
        public int EmployeeAttendanceId { get; set; }
        public int EmployeeId { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime EmployeeAttendanceDate { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> EmployeeAttendanceComingTime { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> EmployeeAttendanceClosingTime { get; set; }
    
        public virtual TblEmployee TblEmployee { get; set; }
    }
}
