//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEmployeeResume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEmployeeResume()
        {
            this.TblEmployeeCertificates = new HashSet<TblEmployeeCertificate>();
            this.TblEmployeeEducations = new HashSet<TblEmployeeEducation>();
            this.TblEmployeeLanguages = new HashSet<TblEmployeeLanguage>();
            this.TblEmployeeSkills = new HashSet<TblEmployeeSkill>();
            this.TblEmployeeWorkExperiences = new HashSet<TblEmployeeWorkExperience>();
        }
    
        public int EmployeeResumeId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeResumeFirstName { get; set; }
        public string EmployeeResumeLastName { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EmployeeResumeDateOfBirth { get; set; }
        public string EmployeeResumeNationality { get; set; }
        public string EmployeeResumeEducationLevel { get; set; }
        public string EmployeeResumeAddress { get; set; }
        public string EmployeeResumeContactNo { get; set; }
        public string EmployeeResumeEmail { get; set; }
        public string EmployeeResumeSummary { get; set; }
        public string EmployeeResumeLinkIn { get; set; }
        public string EmployeeResumeFacebook { get; set; }
        public string EmployeeResumeTwitter { get; set; }
        public string EmployeeResumeImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployeeCertificate> TblEmployeeCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployeeEducation> TblEmployeeEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployeeLanguage> TblEmployeeLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployeeSkill> TblEmployeeSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployeeWorkExperience> TblEmployeeWorkExperiences { get; set; }
    }
}
