//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExamMark
    {
        public int ExamMarksId { get; set; }
        public int ExamId { get; set; }
        public int ClassId { get; set; }
        public int StudentId { get; set; }
        public int UserId { get; set; }
        public double ExamMarksTotal { get; set; }
        public double ExamMarksObtain { get; set; }
    
        public virtual TblClass TblClass { get; set; }
        public virtual TblExam TblExam { get; set; }
        public virtual TblStudent TblStudent { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
