//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExamSetting
    {
        public int ExamSettingId { get; set; }
        public int UserId { get; set; }
        public int SessionId { get; set; }
        public int ExamId { get; set; }
        public int ProgrammeSessionId { get; set; }
        public string ExamSettingDescription { get; set; }
    
        public virtual TblExam TblExam { get; set; }
        public virtual TblProgrammeSession TblProgrammeSession { get; set; }
        public virtual TblSession TblSession { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
