//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployeeLanguage
    {
        public int EmployeeLanguageId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> EmployeeResumeId { get; set; }
        public string EmployeeLanguageName { get; set; }
        public string EmployeeLanguageProficiency { get; set; }
    
        public virtual TblEmployeeResume TblEmployeeResume { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
