//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblExam()
        {
            this.TblExamMarks = new HashSet<TblExamMark>();
            this.TblExamSettings = new HashSet<TblExamSetting>();
            this.TblTimes = new HashSet<TblTime>();
        }
    
        public int ExamId { get; set; }
        public int UserId { get; set; }
        public string ExamTitle { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ExamStartDate { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ExamEndDate { get; set; }
        public string ExamDescription { get; set; }
    
        public virtual TblUser TblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblExamMark> TblExamMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblExamSetting> TblExamSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTime> TblTimes { get; set; }
    }
}
