//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class TblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEmployee()
        {
            this.TblEmployeeAttendances = new HashSet<TblEmployeeAttendance>();
            this.TblEmployeeLeavings = new HashSet<TblEmployeeLeaving>();
            this.TblEmployeeSalaries = new HashSet<TblEmployeeSalary>();
        }
    
        public int EmployeeId { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Required Field")]
        public int DesignationId { get; set; }
        [Required(ErrorMessage ="{0} Required Field")]
        public string EmployeeName { get; set; }
        [Required(ErrorMessage = "Required Field")]
        public string EmployeeContactNo { get; set; }
        public string EmployeeEmailAddress { get; set; }
        [Required(ErrorMessage = "Required Field")]
        public string EmployeeAddress { get; set; }
        [Required(ErrorMessage = "Required Field")]
        public string EmployeeQualification { get; set; }
        public string EmployeePhoto { get; set; }
        public string EmployeeDescription { get; set; }
        [Required(ErrorMessage = "Required Field")]
        public double EmployeeBasicSalary { get; set; }
        public bool EmployeeStatus { get; set; }
        public string EmployeeGender { get; set; }
        public string EmployeeHomeContactNo { get; set; }
        public bool EmployeeDoYouHaveAnyDisability { get; set; }
        public string EmployeeIfDisabilityYesGiveIssue { get; set; }
        public bool EmployeeDoYouTakingAnyMedication { get; set; }
        public string EmployeeIfMedicationYesGiveIssue { get; set; }
        public bool EmployeeAnyCreminalOffCenceAgain { get; set; }
        public string EmployeeIfCreminalOffCenceAgainYesGiveIssue { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime EmployeeRegistrationDate { get; set; }

        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }
    
        public virtual TblDesignation TblDesignation { get; set; }
        public virtual TblUser TblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployeeAttendance> TblEmployeeAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployeeLeaving> TblEmployeeLeavings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmployeeSalary> TblEmployeeSalaries { get; set; }
    }
}
