//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSubmissionFee
    {
        public int SubmissionFeeId { get; set; }
        public int UserId { get; set; }
        public int StudentId { get; set; }
        public int ProgrammeId { get; set; }
        public int ClassId { get; set; }
        public double SubmissionFeeAmount { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime SubmissionFeeDate { get; set; }
        public string SubmissionFeeMonth { get; set; }
        public string SubmissionFeeDescription { get; set; }
    
        public virtual TblClass TblClass { get; set; }
        public virtual TblProgramme TblProgramme { get; set; }
        public virtual TblStudent TblStudent { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
