//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblStudentAttendance
    {
        public int StudentAttendanceId { get; set; }
        public int StudentId { get; set; }
        public int ClassId { get; set; }
        public int SessionId { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime StudentAttendanceDate { get; set; }
        [DataType(DataType.Time)]
        public System.TimeSpan StudentAttendanceTime { get; set; }
    
        public virtual TblClass TblClass { get; set; }
        public virtual TblSession TblSession { get; set; }
        public virtual TblStudent TblStudent { get; set; }
    }
}
