//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSubject()
        {
            this.TblClassSubjects = new HashSet<TblClassSubject>();
            this.TblSessionProgrammeSubjectSettings = new HashSet<TblSessionProgrammeSubjectSetting>();
            this.TblTimes = new HashSet<TblTime>();
        }
    
        public int SubjectId { get; set; }
        public int UserId { get; set; }
        public string SubjectName { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime SubjectRegistrationDate { get; set; }
        public string SubjectDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblClassSubject> TblClassSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionProgrammeSubjectSetting> TblSessionProgrammeSubjectSettings { get; set; }
        public virtual TblUser TblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTime> TblTimes { get; set; }
    }
}
