//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSession()
        {
            this.TblExamSettings = new HashSet<TblExamSetting>();
            this.TblProgrammeSessions = new HashSet<TblProgrammeSession>();
            this.TblStudentPromots = new HashSet<TblStudentPromot>();
            this.TblSessionProgrammeSubjectSettings = new HashSet<TblSessionProgrammeSubjectSetting>();
            this.TblStudents = new HashSet<TblStudent>();
            this.TblStudentAttendances = new HashSet<TblStudentAttendance>();
        }
    
        public int SessionId { get; set; }
        public int UserId { get; set; }
        public string SessionName { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime SessionStartDate { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime SessionEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblExamSetting> TblExamSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProgrammeSession> TblProgrammeSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudentPromot> TblStudentPromots { get; set; }
        public virtual TblUser TblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionProgrammeSubjectSetting> TblSessionProgrammeSubjectSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudent> TblStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudentAttendance> TblStudentAttendances { get; set; }
    }
}
